### ISSUE TITLE
Cannot add new node with right-click menu and cannot paste nodes

### ISSUE THREAD

**Issue by Anutpattika** [campsych/concerto-platform#239]
### Concerto Platform version
v5.0.beta.10.1

### Expected behavior
New nodes is added upon selecting items in right click menu. 
Copied nodes should be able to be pasted.

### Actual behavior
Nothing returns.

### Steps to reproduce the issue
In flowchart, right-click and then select any node to add or paste.

**Comment by assessment4learning** [comment]
I tested for the above issue for a few hours previously, both on PC and Mac. Surely it happened continuously for beta 10 but not beta 7. But it just becomes normal again a few minutes ago. May be it is caused by some external library and fixed automatically few minutes ago? Issue no more there but I post my comment here FYI.

**Comment by Anutpattika** [comment]
The above issue has already been fixed in an elegant way. 
https://github.com/campsych/concerto-platform/commit/6d7fea3b508a64e165f392fe6d49c8c09424d049

**Comment by vamcumn** [comment]
I am still facing this issue..right click does not add new nodes to the flow chart...can anybody please help??
